apiVersion: v1
kind: ConfigMap
metadata:
  name: "java-config"
data:
  java-opts: |-
    # Not sure how to use this part as an env variable
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+UseCGroupMemoryLimitForHeap"

  server.properties: |-
    allow-flight=false
    allow-nether=true
    difficulty=3
    enable-query=false
    # Need to look into rcon
    enable-rcon=false 
    enable-command-block=false
    force-gamemode=false
    gamemode=0
    generate-structures=true
    generator-settings=
    hardcore=false
    # Specify the relative path FROM world/. A volume is attached to ./world,
    # so it's super important to prefix your world name with world/
    # YOU WILL LOSE YOUR DATA OTHERWISE
    level-name=world/minekube
    level-seed=
    level-type="DEFAULT"
    max-build-height=256
    # Custom
    max-players=10 
    max-tick-time=60000
    max-world-size=29999984
    motd="MineKube: Java Edition"
    network-compression-threshold=256
    online-mode=true
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=true
    query.port=25565
    rcon.password=
    rcon.port=25575
    resource-pack=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    # Custom
    snooper-enabled=false
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    use-native-transport=true
    view-distance=10
    white-list=false
    enforce-whitelist=false
