apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: "minecraft-external"
  spec:
    selector:
      appType: "hosted-games"
      appName: "minecraft"
      app: "minecraft"
    ports:
    - protocol: TCP
      port: 25565
      targetPort: minecraft-svc
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      appType: "hosted-games"
      appName: "minecraft"
      app: "minecraft"
    name: "minecraft"
  spec:
    replicas: 1
    selector:
      matchLabels:
        appType: "hosted-games"
        appName: "minecraft"
        app: "minecraft"
    template:
      metadata:
        labels:
          appType: "hosted-games"
          appName: "minecraft"
          app: "minecraft"
      spec:
        containers:
        - name: "minecraft"
          # Change the image to your repository path
          image: minecraft-java:v1.13.1
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar", "/app/server.jar", "nogui"]
          ports:
          - name: minecraft-svc
            containerPort: 25565
          # Liveness/Readiness based on serving port
          readinessProbe:
            tcpSocket:
              port: minecraft-svc
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: minecraft-svc
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
