apiVersion: v1
items:
#- apiVersion: v1
#  kind: Service
#  metadata:
#    name: "minecraft-v6-svc"
#  spec:
#    selector:
#      appType: "hosted-games"
#      appName: "minecraft"
#      app: "minecraft"
#    ports:
#    - protocol: UDP
#      port: 19133
#      targetPort: mc-v6-svc
#    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: "minecraft-v4-svc"
  spec:
    selector:
      appType: "hosted-games"
      appName: "minecraft"
      app: "minecraft"
    ports:
    - protocol: UDP
      port: 19132
      targetPort: mc-v4-svc
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      appType: "hosted-games"
      appName: "minecraft"
      app: "minecraft"
    name: "minecraft"
  spec:
    replicas: 1
    selector:
      matchLabels:
        appType: "hosted-games"
        appName: "minecraft"
        app: "minecraft"
    template:
      metadata:
        labels:
          appType: "hosted-games"
          appName: "minecraft"
          app: "minecraft"
      spec:
        containers:
        - name: "minecraft"
          # Change the image to your repository path
          image: minecraft-bedrock:1.6.1.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: mc-v4-svc
            containerPort: 19132
            protocol: UDP
          - name: mc-v6-svc
            containerPort: 19133
            protocol: UDP
          # Liveness/Readiness based on serving port
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
