apiVersion: v1
kind: Service
metadata:
  name: nextcloud-app-svc
  labels:
    app: nextcloud
    component: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nextcloud
    component: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-app
  labels:
    app: nextcloud
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: web
  template:
    metadata:
      labels:
        app: nextcloud
        component: web
    spec:
      containers:
      - name: nextcloud
        image: registry.hub.docker.com/library/nextcloud:14.0.7-apache
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-data
        ports:
        - containerPort: 80
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
        #emptyDir: {}
