apiVersion: v1
namespace: logging
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      appType: "infra-logging"
      appName: "elasticstack"
    name: "elasticsearch"
  spec:
    replicas: 1
    selector:
      matchLabels:
        appType: "infra-logging"
        appName: "elasticstack"
        app: "elasticsearch"
    template:
      metadata:
        labels:
          appType: "infra-logging"
          appName: "elasticstack"
          app: "elasticsearch"
      spec:
        containers:
        - name: "elasticsearch"
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      appType: "infra-logging"
      appName: "elasticstack"
    name: "logstash"
  spec:
    replicas: 1
    selector:
      matchLabels:
        appType: "infra-logging"
        appName: "elasticstack"
        app: "logstash"
    template:
      metadata:
        labels:
          appType: "infra-logging"
          appName: "elasticstack"
          app: "logstash"
      spec:
        containers:
        - name: "logstash"
          image: docker.elastic.co/logstash/logstash:6.4.0
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      appType: "infra-logging"
      appName: "elasticstack"
    name: "kibana"
  spec:
    replicas: 1
    selector:
      matchLabels:
        appType: "infra-logging"
        appName: "elasticstack"
        app: "kibana"
    template:
      metadata:
        labels:
          appType: "infra-logging"
          appName: "elasticstack"
          app: "kibana"
      spec:
        containers:
        - name: "kibana"
          image: docker.elastic.co/kibana/kibana:6.4.0
          imagePullPolicy: IfNotPresent
        restartPolicy: Always
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
