apiVersion: v1
items:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: yourWorldClaimHere
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  name: 
    storageClassName: do-block-retain
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: yourLogClaimHere
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: do-block-retain
kind: List
