# This will run up your bill significantly, so make sure you have a tool to
# recycle your unused volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: do-block-retain
  namespace: ""
provisioner: com.digitalocean.csi.dobs
reclaimPolicy: Retain
volumeBindingMode: Immediate
