apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
  - name: minecraft-node
    port: 25565
    protocol: TCP
    targetPort: minecraft-svc
  selector:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
