apiVersion: v1
kind: Service
metadata:
  name: mediawiki-app
  labels:
    app: mediawiki
    component: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mediawiki
    component: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-app
  labels:
    app: mediawiki
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
      component: web
  template:
    metadata:
      labels:
        app: mediawiki
        component: web
    spec:
      containers:
      - name: mediawiki
        image: registry.hub.docker.com/library/mediawiki:1.31.1
        volumeMounts:
        - mountPath: /var/www/data
          name: mediawiki-db-data
        - mountPath: /var/www/html/images
          name: mediawiki-data
        #- mountPath: /var/www/html/LocalSettings.php
        #  subPath: LocalSettings.php 
        #  name: mediawiki-config
        ports:
        - containerPort: 80
      volumes:
      - name: mediawiki-data
        persistentVolumeClaim:
          claimName: mediawiki-data
      - name: mediawiki-config
        configMap:
          name: mediawiki-config
          items:
            - key: LocalSettings.php
              path: LocalSettings.php
        #emptyDir: {}
