apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: "factorio"
  spec:
    selector:
      app: "factorio"
    ports:
    - protocol: UDP
      port: 34197
      targetPort: factorio
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "factorio"
    name: "factorio"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "factorio"
    template:
      metadata:
        labels:
          app: "factorio"
      spec:
        containers:
        - name: "factorio"
          # Change the image to your repository path, or build your own
          #image: factorio:0.16.51
          imagePullPolicy: IfNotPresent
          stdin: false
          tty: false
          ports:
          - name: factorio
            containerPort: 34197
            protocol: UDP
          volumeMounts:
          - name: world-data
            mountPath: /opt/factorio/saves
        volumes:
        # EmptyDir for world
        - name: world-data
        #  persistentVolumeClaim:
        #    claimName: yourWorldClaimHere
          emptyDir: {}
        #imagePullSecrets:
        #- name: yourRegistrySecretsHere
    strategy:
      type: "Recreate"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
