apiVersion: v1
kind: ConfigMap
data:
  serverconfig.txt: |-
    # Load a world and automatically start the server.
    world=Worlds/tk8s.wld
    # Sets the folder where world files will be stored
    worldpath=Worlds/
    #Sets the name of the world when using autocreate
    worldname=tk8s
    # Creates a new world if none is found. World size is specified by: 1(small), 2(medium), and 3(large).
    autocreate=2
    #Sets the world seed when using autocreate
    #seed=
    #Sets the difficulty of the world when using autocreate 0(normal), 1(expert)
    difficulty=0
    #Sets the max number of players allowed on a server.  Value must be between 1 and 255
    maxplayers=8
    #Set the server password
    #password=
    #Set the message of the day
    motd=Terraria on Kubernetes!
    #The location of the banlist. Defaults to "banlist.txt" in the working directory.
    banlist=banlist.txt
    #Adds addition cheat protection.
    secure=1
    #Sets the server language from its language code. 
    #English = en-US, German = de-DE, Italian = it-IT, French = fr-FR, Spanish = es-ES, Russian = ru-RU, Chinese = zh-Hans, Portuguese = pt-BR, Polish = pl-PL,
    language=en-US
    #Reduces enemy skipping but increases bandwidth usage. The lower the number the less skipping will happen, but more data is sent. 0 is off.
    npcstream=60
    #Default system priority 0:Realtime, 1:High, 2:AboveNormal, 3:Normal, 4:BelowNormal, 5:Idle
    priority=0
    #Set the port number
    port=7777
    #Automatically forward ports with uPNP
    upnp=0
metadata:
  name: "terraria-config"
